### ISSUE TITLE
Why remove nodeSelector/affinity/tolerations?

### ISSUE THREAD

**Issue by LeoLiuYan** [virtual-kubelet/tensile-kube#37]
https://github.com/virtual-kubelet/tensile-kube/blob/79ac0394c93acf7036ff302438b2abc7993da495/pkg/util/conversions.go#L49

When create pod from upper cluster to lower cluster,  the code do this: remove nodeSelector and affinity and toleration if annotation is nil,  if some case, we should not remove those attributes from pod's spec if the annotation is nil. 
So, if a better way to decide to remove or reserve nodeSelector or affinity or toleration?

**Comment by cwdsuzhou** [comment]
We would remove some info when scheduling it in upper cluster and add it to annotation. Because this info may cause pod can not be scheduled.

This info would recover when it is scheduled to lower cluster

**Comment by LeoLiuYan** [comment]
But in upper cluster who add annotations?
