### ISSUE TITLE
The purpose of upper and lower clusters

### ISSUE THREAD

**Issue by Jeffwan** [virtual-kubelet/tensile-kube#67]
**Describe the problem**

I don't quite understand design purpose here. Seems all the user requests will come to upper cluster? Lower cluster is used to provide resources for upper cluster? As you mention most of the cluster are small clusters ("e.g. we have 10 clusters but each cluster only has 100 nodes.") Why not to create 1000 nodes cluster as upper cluster and don't use VK to extend it? 

Copy services, secrets from upper cluster to lower cluster is kind of tricky. You also need to make sure connectivity across clusters. What's more, total number of objects in upper cluster never reduces, they are all replicate to lower clusters. This doesn't seem helpful on the scalability side. Maybe I understand wrong, scalability is not the major motivation to create this solution

Another thing I am not sure if all your lower clusters share one etcd for k8s objects? You mention flannel uses same CIDR and it helps to flat ip spaces across all clusters. Do you just use etcd for flannel or for k8s as well?

**Comment by cwdsuzhou** [comment]
> I don't quite understand design purpose here. Seems all the user requests will come to upper cluster? Lower cluster is used to provide resources for upper cluster? As you mention most of the cluster are small clusters ("e.g. we have 10 clusters but each cluster only has 100 nodes.") Why not to create 1000 nodes cluster as upper cluster and don't use VK to extend it?

1. Each lower cluster is more 1000 nodes in our environment, we have more than 100 cluster(not all 1000 nodes). Through VK,  our cluster is more than 15000 nodes now. Original K8s may only support 5000 nodes. 
2. multicluster scheduling which is benefit for users to deploy applications not only in one cluster.
3. Our initial purpose is combine the cluster resource fragments.

> Another thing I am not sure if all your lower clusters share one etcd for k8s objects? You mention flannel uses same CIDR and it helps to flat ip spaces across all clusters. Do you just use etcd for flannel or for k8s as well?

A single etcd for flannel.

**Comment by Jeffwan** [comment]
@cwdsuzhou Thanks for your quick response. It makes more sense now if there're 15k nodes in total.  Seems your org is the only user of upper cluster and this way help resolve federation problem.  Have you consided multi-cluster management like kubernetes federation instead?

**Comment by cwdsuzhou** [comment]
federation only helps allocate replicas, e.g. deployment, replicaSet, not scheduling pods. What's more, pods created by operators may not work with deployment or replicaSet.

**Comment by Jeffwan** [comment]
Thanks for the reply. I will close the issue.
