### ISSUE TITLE
终止virtual-node进程，并删除virtual-kubelet节点后，仍然会调度的问题

### ISSUE THREAD

**Issue by wuzhengxuan** [virtual-kubelet/tensile-kube#72]
有个问题想咨询一下
有个B集群有5台机器，A集群3台机器
我在X物理机上启动了virtual-node，并设置了--kubeconfig为A集群的配置，--client-kubeconfig为B集群的配置
然后在A集群看到了这个virtual-kubelet，并可以调度资源到B集群上，非常棒
但是，我停止了virtual-node进程，并在A集群删除了virtual-kubelet节点后，仍然会调度到B集群，请问是我停止和删除的动作不对么？

**Comment by cwdsuzhou** [comment]
Please use English.

From the prospect of scheduler,  node and virtual-node  are same. I am not sure what K8s  version you are using.  I am afraid this is  a bug of   scheduler.

**Comment by wuzhengxuan** [comment]
thanks
I am going to check my scheduler
