### ISSUE TITLE
Is single etcd cluster required ?

### ISSUE THREAD

**Issue by grosser** [virtual-kubelet/tensile-kube#76]
https://github.com/virtual-kubelet/tensile-kube#use-case suggests that all clusters should talk to the same etcd, is that a requirement or just an example ?
Also the image shows the api in the lower cluster talking to a different etcd, is that intended ?
(also there is only bug template for issues)

**Comment by cwdsuzhou** [comment]
> https://github.com/virtual-kubelet/tensile-kube#use-case suggests that all clusters should talk to the same etcd, is that a requirement or just an example ?

Just an example.

> Also the image shows the api in the lower cluster talking to a different etcd, is that intended ?
> (also there is only bug template for issues)

Yes, clusters are independent.

**Comment by grosser** [comment]
thx for the clarification

for improvement ideas:
- make the image point at different etcds
- make the api also point at the same etcd
- add image source so others can make PRs
- align the boxes
<img width="104" alt="Screen Shot 2021-07-09 at 9 46 47 AM" src="https://user-images.githubusercontent.com/11367/125111460-c9ca5d00-e09a-11eb-8f4d-050bd329e457.png">

**Comment by cwdsuzhou** [comment]
> thx for the clarification
> 
> for improvement ideas:
> 
> * make the image point at different etcds
> * make the api also point at the same etcd
> * add image source so others can make PRs
> * align the boxes
> 
> <img alt="Screen Shot 2021-07-09 at 9 46 47 AM" width="104" src="https://user-images.githubusercontent.com/11367/125111460-c9ca5d00-e09a-11eb-8f4d-050bd329e457.png">

Thanks, this is only a use case to make different clusters communicate. If not apply the case, clusters within the same vpc can also can achieve the goals if deploying on Cloud.
