### ISSUE TITLE
error building in cluster config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined 

### ISSUE THREAD

**Issue by william-lbn** [virtual-kubelet/tensile-kube#82]
deploy the virtual node   binary 
```
./bin/virtual-node --nodename 192.168.1.14 --provider k8s --kube-api-qps 500 --kube-api-burst 1000 --client-qps 500 --client-burst 1000 --kubeconfig /root/certs/master/admin.config  --client-kubeconfig /root/certs/node/admin.config
```
```
FATA[0000] error building in cluster config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined 
```

when  set 

export KUBERNETES_SERVICE_HOST=192.168.1.70
export KUBERNETES_SERVICE_PORT=6443

```
root@virtual-kubelet:~/tensile-kube# ./bin/virtual-node --nodename 192.168.1.14 --provider k8s --kube-api-qps 500 --kube-api-burst 1000 --client-qps 500 --client-burst 1000 --kubeconfig /root/certs/master/admin.config  --client-kubeconfig /root/certs/node/admin.config
Error: error building in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
Usage:
  virtual-node [flags]
  virtual-node [command]

Available Commands:
  help        Help about any command
  providers   Show the list of supported providers
  version     Show the version of the program
```

binary deployment description is very simple，how to solve it?

**Comment by cwdsuzhou** [comment]
> --kubeconfig /root/certs/master/admin.config

is this path exits? if not, it will run as `InCluster`

**Comment by william-lbn** [comment]
> > --kubeconfig /root/certs/master/admin.config
> 
> Does this path exits? if not, it will run as `InCluster`

thank you for your reply.   remote debug found that the path was not exists. 

```
// Check if the kubeConfig file exists.
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		// Get the kubeconfig from the filepath.
		config, err = clientcmd.BuildConfigFromFlags("", configPath)
		if err != nil {
			return nil, errors.Wrap(err, "error building client config")
		}
	} else {
		// Set to in-cluster config.
		config, err = rest.InClusterConfig()
		if err != nil {
			return nil, errors.Wrap(err, "error building in cluster config")
		}
	}
```

I think maybe add a log here

**Comment by cwdsuzhou** [comment]
> > > --kubeconfig /root/certs/master/admin.config
> > 
> > 
> > Does this path exits? if not, it will run as `InCluster`
> 
> thank you for your reply. remote debug found that the path was not exists.
> 
> ```
> // Check if the kubeConfig file exists.
> 	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
> 		// Get the kubeconfig from the filepath.
> 		config, err = clientcmd.BuildConfigFromFlags("", configPath)
> 		if err != nil {
> 			return nil, errors.Wrap(err, "error building client config")
> 		}
> 	} else {
> 		// Set to in-cluster config.
> 		config, err = rest.InClusterConfig()
> 		if err != nil {
> 			return nil, errors.Wrap(err, "error building in cluster config")
> 		}
> 	}
> ```
> 
> I think maybe add a log here

You can open a PR to do this if you  like, thanks!

**Comment by william-lbn** [comment]
> > > > --kubeconfig /root/certs/master/admin.config
> > > 
> > > 
> > > Does this path exits? if not, it will run as `InCluster`
> > 
> > 
> > thank you for your reply. remote debug found that the path was not exists.
> > ```
> > // Check if the kubeConfig file exists.
> > 	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
> > 		// Get the kubeconfig from the filepath.
> > 		config, err = clientcmd.BuildConfigFromFlags("", configPath)
> > 		if err != nil {
> > 			return nil, errors.Wrap(err, "error building client config")
> > 		}
> > 	} else {
> > 		// Set to in-cluster config.
> > 		config, err = rest.InClusterConfig()
> > 		if err != nil {
> > 			return nil, errors.Wrap(err, "error building in cluster config")
> > 		}
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think maybe add a log here
> 
> You can open a PR to do this if you like, thanks!


done
